# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      dynamic-matrix: ${{ steps.export-dynamic-matrix.outputs.dynamic-matrix }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Export deployment matrix
        id: export-dynamic-matrix
        run: |
          JSON="$(cat ./matrix.json)"
          JSON="${JSON//'%'/'%25'}"
          JSON="${JSON//$'\n'/'%0A'}"
          JSON="${JSON//$'\r'/'%0D'}"
          echo "::set-output name=dynamic-matrix::$JSON"

  job2:
    name: "${{ matrix.client.project }}: Prepare release"
    runs-on: ubuntu-latest
    needs: job1
    strategy:
      matrix:
        client: ${{ fromJson(needs.job1.outputs.dynamic-matrix) }}
    steps:
      - name: print results
        id: print-results
        run: |
          echo "project ${{ matrix.client.project }}"
          echo "config ${{ matrix.client.config }}"
